version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.4.2 # dockerhub
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # 阿里云
    container_name: pg
    restart: always
    ports:
      - 8100:5432
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=fastgpt
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastgpt
    volumes:
      # 刚创建的文件
      - /root/fastgpt/pg/init.sql:/docker-entrypoint-initdb.d/init.sh
      - /root/fastgpt/pg/data:/var/lib/postgresql/data
  mongodb:
    image: mongo:5.0.18
    # image : registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /root/fastgpt/mongo/data:/data/db
      - /root/fastgpt/mongo/logs:/var/log/mongodb
  fastgpt:
    image: ghcr.io/c121914yu/fastgpt:latest # github
    # image: c121914yu/fast-gpt:latest # docker hub
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
    network_mode: host
    restart: always
    container_name: fastgpt
    environment: # 可选的变量，不需要的话需要去掉
      - PORT=3000 # 运行的端口地址，如果不是 3000，需要修改成实际地址。
      - DB_MAX_LINK=15 # database max link
      # proxy（可选）
      - AXIOS_PROXY_HOST=127.0.0.1
      - AXIOS_PROXY_PORT=7890
      # 发送邮箱验证码配置。用的是QQ邮箱。参考 nodeMail 获取MAILE_CODE，自行百度。
      - MY_MAIL=54545@qq.com
      - MAILE_CODE=1234
      # 阿里短信服务（邮箱和短信至少二选一）
      - aliAccessKeyId=xxxx
      - aliAccessKeySecret=xxxx
      - aliSignName=xxxxx
      - aliTemplateCode=SMS_xxxx
      # google V3 安全校验（可选）
      - CLIENT_GOOGLE_VER_TOKEN=xxx
      - SERVICE_GOOGLE_VER_TOKEN=xx
      # token加密凭证（随便填，作为登录凭证）
      - TOKEN_KEY=xxxx
      # root key, 最高权限，可以内部接口互相调用
      - ROOT_KEY=xxx
      # 和上方mongo镜像的username,password对应
      - MONGODB_URI=mongodb://username:password@0.0.0.0:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      - PG_HOST=0.0.0.0
      - PG_PORT=8100
      # 和上方PG镜像对应.
      - PG_USER=fastgpt
      - PG_PASSWORD=1234
      - PG_DB_NAME=fastgpt
      # openai
      # 对话用的key，多个key，逗号分开
      - OPENAIKEY=sk-xxxxx,sk-xxx
      # 训练用的key
      - OPENAI_TRAINING_KEY=sk-xxx,sk-xxxx
      - GPT4KEY=sk-xxx
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_BASE_URL_AUTH=可选的安全凭证
  nginx:
    image: nginx:alpine3.17
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      # 刚创建的文件
      - /root/fastgpt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/fastgpt/nginx/logs:/var/log/nginx
      # https证书，没有的话不填，对应的nginx.conf也要修改
      - /root/fastgpt/nginx/ssl/docgpt.key:/ssl/docgpt.key
      - /root/fastgpt/nginx/ssl/docgpt.pem:/ssl/docgpt.pem
